services:
  db:
    container_name: rss_db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    container_name: rss_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.full
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://pg:pg@db:5432/db
      - FRONT_BASE_URL=http://localhost:3000
      - HOST=0.0.0.0:8080
    stop_grace_period: 5s

  frontend:
    container_name: rss_frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - API_BASE_URL=http://localhost:8080

volumes:
  db_data:
