FROM rust:1.92-alpine AS base
RUN apk add --no-cache musl-dev
RUN rustup target add aarch64-unknown-linux-musl
WORKDIR /app

FROM base AS builder
COPY src src
COPY .sqlx .sqlx
COPY Cargo.toml Cargo.lock .
ENV SQLX_OFFLINE=true
RUN cargo build --locked --release && cp ./target/release/backend backend
RUN chmod +x backend

FROM scratch
COPY --from=builder /app/backend /usr/local/bin/backend
EXPOSE 8000
ENTRYPOINT ["backend"]

